version: "3.4"

services:
  minio:
    image: "minio/minio:latest"

    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090"

    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234

    volumes:
      - "s3-data:/minio/data"

    command: minio server /minio/data --console-address ":9090"

    restart: always

    networks:
      default:
        aliases:
          - test-bucket.s3.minio.ecmwf.int

volumes:
  s3-data:
    driver: local
