version: "3.4"

services:
  minio:
    image: "minio/minio:latest"

    ports:
      - "127.0.0.1:${FORWARD_MINIO_PORT:-9000}:9000"
      - "127.0.0.1:${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090"

    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234

    volumes:
      - ./data:/data
      - ./certs:/root/.minio/certs

    command: minio server /data --console-address ":9090"

    restart: unless-stopped
